In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

import matplotlib.pylab as pylab
import scipy.io

#import pygal

# This import registers the 3D projection, but is otherwise unused.
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 unused import

%matplotlib inline

In [28]:
f6_session1 = np.array()
f6_session2 = np.array()
f6_session3 = np.array()
f6_session4 = np.array()
f6_session5 = np.array()
f6_session6 = np.array()
f6_session7 = np.array()
f6_session8 = np.array()
f6_session9 = np.array()
f6_session10 = np.array()


f75_session1 = np.array()
f75_session2 = np.array()
f75_session3 = np.array()
f75_session4 = np.array()
f75_session5 = np.array()
f75_session6 = np.array()
f75_session7 = np.array()
f75_session8 = np.array()
f75_session9 = np.array()
f75_session10 = np.array()

f85_session1 = np.array()
f85_session2 = np.array()
f85_session3 = np.array()
f85_session4 = np.array()
f85_session5 = np.array()
f85_session6 = np.array()
f85_session7 = np.array()
f85_session8 = np.array()
f85_session9 = np.array()
f85_session10 = np.array()


f10_session1 = np.array()
f10_session2 = np.array()
f10_session3 = np.array()
f10_session4 = np.array()
f10_session5 = np.array()
f10_session6 = np.array()
f10_session7 = np.array()
f10_session8 = np.array()
f10_session9 = np.array()
f10_session10 = np.array()

In [64]:
f6 = np.array([f6_session1,f6_session2,f6_session3,f6_session4,f6_session5,f6_session6,f6_session7,f6_session8,f6_session9,f6_session10])
f75 = np.array([f75_session1 ,f75_session2 ,f75_session3 ,f75_session4 ,f75_session5 ,f75_session6 ,f75_session7 ,f75_session8 ,f75_session9 ,f75_session10 ,])
f85 = np.array([f85_session1 ,f85_session2 ,f85_session3 ,f85_session4 ,f85_session5 ,f85_session6 ,f85_session7 ,f85_session8 ,f85_session9 ,f85_session10 ,])
f10 = np.array([f10_session1 ,f10_session2 ,f10_session3 ,f10_session4 ,f10_session5 ,f10_session6 ,f10_session7 ,f10_session8 ,f10_session9 ,f10_session10 ,])

f_a = np.array([f6 , f75 , f85 , f10])

print(np.mean(f_a , axis=0))

[[[ 2.17089708e+00 -5.47076492e-03]
  [ 6.05112312e-01 -1.97590589e-03]
  [ 4.20456394e-01  3.81250854e-02]
  [-4.52823265e-01 -1.40956770e-02]
  [ 3.65639697e+00 -2.22315859e-02]
  [ 1.03403377e+00  3.08826875e-03]
  [ 9.95109432e-01  2.25878354e-02]
  [ 7.71663276e-01  2.06235030e-02]
  [-7.07440940e-01 -3.49129234e-03]]

 [[-1.51610944e+00 -2.36974925e-03]
  [ 6.21066441e+00  1.24310933e-05]
  [ 4.53847267e+00  3.69500628e-02]
  [ 2.59702115e+00 -1.32228657e-02]
  [ 4.43264707e+00  1.84950768e-03]
  [ 1.51917524e+00  9.00841000e-03]
  [ 5.33267791e+00  1.09862989e-02]
  [ 4.45129578e+00  4.02185305e-01]
  [ 5.55355207e+00 -1.93344988e-01]]

 [[-3.39767875e-01  5.39426825e-03]
  [ 3.03886560e+00 -9.92272650e-03]
  [-1.65828361e+00  4.84663250e-03]
  [ 3.21316176e+00  3.26518362e-02]
  [-1.16723363e+00 -1.62644165e-02]
  [ 1.65577145e-01 -8.43013575e-03]
  [ 3.51423623e+00  8.90017350e-03]
  [-1.85058344e+00  1.26177027e-02]
  [-8.44544813e-01  7.05488708e-03]]

 [[-2.25796667e-01 -3.